# Generated by Django 5.0 on 2023-12-12 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fighters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField()),
                ('date', models.DateField()),
                ('challenger', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='challenger_matches', to='fighters.fighter')),
                ('defender', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='defender_matches', to='fighters.fighter')),
            ],
        ),
    ]
