# Generated by Django 5.0 on 2023-12-12 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0002_initial'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='challenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenger_matches', to='fighters.fighter'),
        ),
        migrations.AlterField(
            model_name='match',
            name='defender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defender_matches', to='fighters.fighter'),
        ),
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(choices=[('To be disputed', 'To be disputed'), ('Challenger', 'Challenger'), ('Defender', 'Defender'), ('Draw', 'Draw')], default='To be disputed'),
        ),
    ]
