# Generated by Django 5.0 on 2023-12-08 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0002_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField()),
                ('date', models.DateField()),
                ('challenger', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Fighter1', to='fighters.fighter')),
                ('defender', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Fighter2', to='fighters.fighter')),
                ('title', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fighters.title')),
            ],
        ),
    ]
