# Generated by Django 5.0 on 2023-12-18 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0003_remove_fighter_titles_alter_fighter_picture'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fighter',
            unique_together={('first_name', 'last_name')},
        ),
    ]
