# Generated by Django 5.0 on 2023-12-08 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0003_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='title',
        ),
    ]
