# Generated by Django 5.0 on 2023-12-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0004_alter_fighter_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
