# Generated by Django 5.0 on 2023-12-09 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0004_remove_match_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='date',
        ),
        migrations.RemoveField(
            model_name='title',
            name='fighter',
        ),
        migrations.AddField(
            model_name='fighter',
            name='title',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fighters.title'),
        ),
    ]
