# Generated by Django 5.0 on 2023-12-09 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fighters', '0005_remove_title_date_remove_title_fighter_fighter_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fighters.title'),
        ),
    ]
